### PR TITLE
Remove "hack" in OnlineMigrator to remove error in latest Laravel version

### PR DESCRIPTION
**Pull request by imTigger**
Solves #15

### CODE REVIEW

**Comment by paulrrogers** [comment]
Thanks for the feedback. Does v5.8 output the "Migrating …" message before the PTOSC output without this hack? Or does it appear afterward?

Any chance you could leave the old 'hack' with a v5.7-or-earlier conditional so that those not yet on v5.8 will still get consistent behavior?

**Comment by imTigger** [comment]
The message show up as error (in red) before any actual operation.
Therefore no migration/command was run.

I checked the commit log of Laravel framework, it seems broken since 5.8.26
https://github.com/laravel/framework/commits/bca599bfe6404e9b9be552810a1102bfe2a7893a/src/Illuminate/Database/Migrations/Migrator.php

**Comment by imTigger** [comment]
I am not familar with the original behavior.
Are there ways to archive the same effect without using $notes?

**Comment by paulrrogers** [comment]
Superseded by #17

**Pull request closed without merging**
